const http=require('http'),fs=require('fs'),fsp=require('fs/promises'),path=require('path');
const ROOT=__dirname,PORT=Number(process.env.PORT||8082),PUBLIC_DIR=path.join(ROOT,'public'),DATA_DIR=path.join(ROOT,'data'),LOG_DIR=path.join(ROOT,'logs'),RUN_LOG=path.join(LOG_DIR,'run.log');
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8'};
for(const d of[DATA_DIR,LOG_DIR])fs.mkdirSync(d,{recursive:true});
function log(line){const ts=new Date().toISOString().replace('T',' ').slice(0,19);fs.appendFile(RUN_LOG,`[${ts}] ${line}\n`,()=>{})}
function json(res,status,payload){const body=JSON.stringify(payload);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body)});res.end(body)}
function collectJson(req){return new Promise((resolve,reject)=>{const chunks=[];let total=0;req.on('data',(chunk)=>{total+=chunk.length;if(total>50*1024*1024){reject(new Error('request too large'));req.destroy();return}chunks.push(chunk)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
async function serveFile(res,filePath){try{const stat=await fsp.stat(filePath);if(!stat.isFile())throw new Error('not file');res.writeHead(200,{'Content-Type':MIME[path.extname(filePath)]||'application/octet-stream'});fs.createReadStream(filePath).pipe(res)}catch{res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});res.end('Not Found')}}
function demoLocate(payload){const width=Number(payload.width||1280),height=Number(payload.height||720),label=payload.query||payload.classes||'LocateAnything';const x=Math.round(width*.34),y=Math.round(height*.28),w=Math.round(width*.28),h=Math.round(height*.28);return{label,bbox:[x,y,x+w,y+h],confidence:.88,note:'Demo locate result. Replace demoLocate() with real LocateAnything worker integration when ready.'}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://127.0.0.1:${PORT}`);log(`${req.method} ${url.pathname}`);try{if(req.method==='GET'&&url.pathname==='/health'){json(res,200,{ok:true,app:'LocateAnything Simple Video Annotator',port:PORT});return}if(req.method==='POST'&&url.pathname==='/api/save'){const payload=await collectJson(req);const file=path.join(DATA_DIR,'annotations.json');await fsp.writeFile(file,JSON.stringify({...payload,saved_at:new Date().toISOString()},null,2));json(res,200,{ok:true,path:file,annotations:payload.annotations?.length||0});return}if(req.method==='POST'&&url.pathname==='/api/locate'){const payload=await collectJson(req);json(res,200,{ok:true,result:demoLocate(payload)});return}const requestPath=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));const target=path.normalize(path.join(PUBLIC_DIR,requestPath));if(!target.startsWith(PUBLIC_DIR)){json(res,403,{ok:false,error:'forbidden'});return}await serveFile(res,target)}catch(error){log(`ERROR ${error.stack||error.message}`);json(res,500,{ok:false,error:error.message})}});
server.listen(PORT,'0.0.0.0',()=>{log(`listening on ${PORT}`);console.log(`LocateAnything simple annotator: http://127.0.0.1:${PORT}`)});
